### ISSUE TITLE
iOS : "Only one operation can be active at a time"

### ISSUE THREAD

**Issue by johankson** [LeoJHarris/FilePicker#5]
After selecting a document on iOS and trying to pick another document you get this message?

**Comment by johankson** [comment]
It looks like the call to `CrossFilePicker.Current.PickFile()` never returns even if the GUI is dismissed after picking a file.

**Comment by LeoJHarris** [comment]
@johankson Il check this issue out. I wont be in a position to do a fix for a few days though.

**Comment by LeoJHarris** [comment]
@johankson Should be resolved in the latest version 1.0.3

**Comment by LeoJHarris** [comment]
I have resolved the issue, and new version is available to download from NuGet v1.0.3

**Comment by XnainA** [comment]
@LeoJHarris This Issue is still open i am using NuGet v1.0.3. and in iOS doesn't give file info.

**Comment by LeoJHarris** [comment]
@XnainA you are still seeing the "Only one operation can be active at a time" when picking another file on iOS? Which file info are you referring to specifically? Is the file null? Or path or filename empty?

**Comment by XnainA** [comment]
I am still facing the same issue , at first when i am trying to pick the file it takes some time but no info provided for the file, second time the code showing this error.

**Comment by LeoJHarris** [comment]
Okay oddly this was working for me but perhaps the release build i did was not the working copy and i released that to Nuget. Ill look into this again

**Comment by LeoJHarris** [comment]
Okay this should be resolved now in 1.0.4, I discovered that the issue was indeed initially fixed however I had updated my iOS device after I had made a release and UIDocumentPickerViewController.DidPickDocument was not being raised on iOS 11+ so I have added in some implementation to support iOS 11+and as a result it is now returning and the error message "Only one operation can be active at a time" should not appear.

I the problem still exists let me know, otherwise we can close this issue.
